#pragma config(Sensor, dgtl4,  doublePiston,   sensorDigitalOut)
#pragma config(Sensor, dgtl5,  singlePiston,   sensorDigitalOut)
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftLU,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRU,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLD,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRD,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           midLeft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          midRight,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................

		motor[backLeft] = motor[frontLeft] = vexRT[Ch3];
		motor[backRight] = motor[frontRight] = vexRT[Ch2];

		if (vexRT[Btn7D]) {
			motor[midLeft] = motor[midRight] = -127;
			} else if (vexRT[Btn8D]) {
			motor[midLeft] = motor[midRight] = 127;
			} else {
			motor[midLeft] = motor[midRight] = 0;
		}

		SensorValue[doublePiston] = vexRT[Btn7DXmtr2];
		SensorValue[singlePiston] = vexRT[Btn7DXmtr2];


		motor[liftLD] = vexRT[Ch3Xmtr2];
		motor[liftRD] = vexRT[Ch3Xmtr2];
		motor[liftLU] = vexRT[Ch3Xmtr2];
		motor[liftRU] = vexRT[Ch3Xmtr2];
	}
}
